namespace DebugToolkit
{
    public static class Lang
    {
        // `{}` denotes necessary, `()` a list of specific choices, `[]` optional, `:` denotes a default

        // Command arguments
        public const string
            ADDPORTAL_ARGS = "Requires 1 argument: {portal ('blue'|'celestial'|'gold'|'green'|'void'|'all')}",
            BAN_ARGS = "Requires 1 argument: {player}",
            BIND_ARGS = "Requires 2 arguments: {key} [console_commands]",
            BIND_DELETE_ARGS = "Requires 1 argument: {key}",
            CHANGETEAM_ARGS = "Requires 1 (2 if from server) argument: {team} [player:<self>]",
            CHARGEZONE_ARGS = "Requires 1 argument: {charge}",
            CREATEPICKUP_ARGS = "Requires 1 (3 if from server) argument: {object (item|equip|drone|'lunarcoin'|'voidcoin')} [search ('item'|'equip'|'drone'|'all'|'pickup'):'all'] [pickup_type:'permanent'] player:<self>]",
            CREATEPOTENTIAL_ARGS = "Requires 0 (3 if from server) arguments: [droptable (droptable|'all'):'all'] [count:3] *[player:<self>]",
            DELAY_ARGS = "Requires 2 arguments: {delay} {console_commands}",
            DUMPSTATE_ARGS = "Requires 0 (1 if from server) argument: [target (player|'pinged'):<self>]",
            DUMPSTATS_ARGS = "Requires 1 argument: {body}",
            ENABLE_ARGS = "Requires 0 or 1 arguments: [enable (0|1)]",
            FIXEDTIME_ARGS = "Requires 0 or 1 argument: [time]",
            FORCEWAVE_ARGS = "Requires 0 or 1 argument [wave_prefab]",
            GIVEBUFF_ARGS = "Requires 1 (4 if from server) arguments: {buff} [count:1] [duration:0] [target (player|'pinged'):<self>]",
            GIVEDOT_ARGS = "Requires 1 (4 if from server) argument: {dot} [count:1] [target (player|'pinged'):<self>] [attacker (player|'pinged'):<self>]",
            GIVEEQUIP_ARGS = "Requires 1 (2 if from server) argument: {equip (equip|'random')} [target (player|'pinged'|'evolution'|'simulacrum'|'voidfields'|'devotion'):<self>]",
            RANDOMEQUIP_ARGS = "Requires 0 (1 if from server) argument: [target (player|'pinged'):<self>]",
            GIVEITEM_ARGS = "Requires 1 (3 if from server) argument: {item} [count:1] [item_type:'permanent'] [target (player|'pinged'|'evolution'|'simulacrum'|'voidfields'|'devotion'):<self>]",
            GIVEDRONE_ARGS = "Requires 1 (4 if from server) argument: {drone} [count:1] [droneTier:1] [target (player|'pinged'):<self>]",
            REMOVEALLDRONES_ARGS = "Requires 0 (1 if from server) argument: [target (player|'pinged'):<self>]",
            GIVELUNAR_ARGS = "Requires 0 arguments: [amount:1]",
            GIVEMONEY_ARGS = "Requires 1 argument: {amount} [target (player|'all')]",
            PLAYER_OR_ALL_OPTIONAL_ARGS = "Requires 0 argument: [target (player|'all'):<self>]",
            PLAYER_OR_ALL_ARGS = "Requires 1 argument: {target (player|'all')}",
            SETSTATS_ARGS = "Requires 1 argument: {stat} [amount|'reset'):'reset']  [target (player|'pinged'):<self>]",
            PLAYER_OR_PINGED = "Requires 0 (1 if from server) arguments: [target (player|'pinged'):<self>]",
            PLAYERPINGED_OR_ALL = "Requires 0 (1 if from server) arguments: [target (player|'pinged'|'all'):<self>]",
            HEAL_ARGS = "Requires 1 argument: {amount} [target (player|'pinged'):<self>]",
            HURT_ARGS = "Requires 1 argument: {amount} [target (player|'pinged'):<self>] [direct (0|1):0/false]",
            PLAYER_ARGS = "Requires 1 argument: {player}",
            KILLALL_ARGS = "Requires 0 arguments: [team:Monster&Void]",
            LISTSKIN_ARGS = "Requires 0 arguments: [selection (body|'all'|'body'|'self'):'all']",
            LISTQUERY_ARGS = "Requires 0 arguments: [query]",
            LOADOUTSKIN_ARGS = "Requires 2 argument: {body_name (body|'self')} {skin_index}",
            LOADOUTSKILL_ARGS = "Requires 2 argument: {skill_slot} {skill_variant}",
            NEXTBOSS_ARGS = "Requires 1 argument: {director_card} [count:1] [elite:None]",
            NEXTSTAGE_ARGS = "Requires 0 arguments: [specific_stage]",
            NO_ARGS = "Requires 0 arguments.",
            PERM_MOD_ARGS = "Requires 2 arguments: {permission_level} {player}",
            POSTSOUNDEVENT_ARGS = "Requires 1 argument: {sound_event (event_name|event_id)}",
            RANDOMITEM_ARGS = "Requires 1 (3 if from server) argument: {count} [droptable (droptable|'all'):'\"Tier1:100,Tier2:60,Tier3:4\"'] [item_type:'permanent'] [target (player|'pinged'|'evolution'|'simulacrum'|'voidfields'|'devotion'):<self>]",
            REMOVEALLBUFFS_ARGS = "Requires 0 (2 if from server) arguments: [timed (0|1):0/false] [target (player|'pinged'):<self>]",
            REMOVEALLDOTS_ARGS = "Requires 0 (1 if from server) arguments: [target (player|'pinged'):<self>]",
            REMOVEALLITEMS_ARGS = "Requires 0 (1 if from server) arguments: [target (player|'pinged'|'evolution'|'simulacrum'|'voidfields'|'devotion'):<self>]",
            REMOVEBUFF_ARGS = "Requires 1 (4 if from server) arguments: {buff} [count:1] [timed (0|1):0/false] [target (player|'pinged'):<self>]",
            REMOVEBUFFSTACKS_ARGS = "Requires 1 (3 if from server) arguments: {buff} [timed (0|1):0/false] [target (player|'pinged'):<self>]",
            REMOVEDOT_ARGS = "Requires 1 (3 if from server) argument: {dot} [count:1] [target (player|'pinged'):<self>]",
            REMOVEDOTSTACKS_ARGS = "Requires 1 (2 if from server) argument: {dot} [target (player|'pinged'):<self>]",
            REMOVEEQUIP_ARGS = "Requires 0 (1 if from server) arguments: [target (player|'pinged'|'evolution'|'simulacrum'|'voidfields'|'devotion'):<self>]",
            REMOVEITEMSTACKS_ARGS = "Requires 1 (2 if from server) argument: {item} [target (player|'pinged'|'evolution'|'simulacrum'|'voidfields'|'devotion'):<self>]",
            RESPAWN_ARGS = "Requires 0 (1 if from server) arguments: [player:<self>]",
            RESTOCKEQUIP_ARGS = "Requires 0 (2 if from server) arguments: [count:1] *[target (player|'pinged'|'evolution'|'simulacrum'|'voidfields'|'devotion'):<self>]",
            RUNSETWAVESCLEARED_ARGS = "Requires 1 argument {wave}",
            SEED_ARGS = "Requires 0 or 1 argument: [new_seed]",
            SETARTIFACT_ARGS = "Requires 1 (2 if using 'all') argument: {artifact (artifact|'all')} [enable (0|1)]",
            SETDIFFICULTY_ARGS = "Requires 1 argument: {difficulty}",
            SPAWNAI_ARGS = "Requires 1 argument: {ai} [count:1] [elite:None] [braindead (0|1):0/false] [team (team|'ally'):Monster]",
            SPAWNAS_ARGS = "Requires 1 (2 if from server) argument: {body} [player:<self>]",
            SPAWNBODY_ARGS = "Requires 1 argument: {body}",
            SPAWNINTERACTABLE_ARGS = "Requires 1 argument: {interactable} [count:1]",
            SPAWNPORTAL_ARGS = "Requires 1 argument: {portal ('artifact'|'blue'|'celestial'|'deepvoid'|'gold'|'green'|'null'|'void')}",
            TIMESCALE_ARGS = "Requires 1 argument: {time_scale}"
            ;

        // Command help texts
        public const string
            ADDPORTAL_HELP = "Add a portal to the current Teleporter on completion. " + ADDPORTAL_ARGS,
            BAN_HELP = "Bans the specified player from the session. " + BAN_ARGS,
            BIND_HELP = "Bind a key to execute specific commands. " + BIND_ARGS,
            BIND_DELETE_HELP = "Remove a custom bind from the macro system of DebugToolkit. " + BIND_DELETE_ARGS,
            BIND_RELOAD_HELP = "Reload the macro system of DebugToolkit. " + NO_ARGS,
            BUDDHA_HELP = "Players become immortal, but remain attackable. " + ENABLE_ARGS,
            BUDDHAENEMY_HELP = "Enemies become immortal, but remain attackable. " + ENABLE_ARGS,
            CHANGETEAM_HELP = "Change the specified player to the specified team. " + CHANGETEAM_ARGS,
            CHARGEZONE_HELP = "Set the charge of all active holdout zones. " + CHARGEZONE_ARGS,
            CREATEPICKUP_HELP = "Creates a PickupDroplet infront of your position. " + CREATEPICKUP_ARGS,
            CREATEPOTENTIAL_HELP = "Creates a potential PickupDroplet infront of your position. " + CREATEPOTENTIAL_ARGS,
            CURSORTELEPORT_HELP = "Teleports you to where your cursor is currently aiming at. " + NO_ARGS,
            GOTOBOSS_HELP = "Teleports you to the Teleporter, first Boss creature or specific arena depending on the stage. " + NO_ARGS,
            DELAY_HELP = "Execute any commands after a delay in seconds. " + DELAY_ARGS,
            DUMPBUFFS_HELP = "List the buffs/debuffs of all spawned bodies. " + NO_ARGS,
            DUMPINVENTORIES_HELP = "List the inventory items and equipment of all spawned bodies. " + NO_ARGS,
            DUMPSTATE_HELP = "List the current stats, entity state, and skill cooldown of a specified body. " + DUMPSTATE_ARGS,
            DUMPSTATS_HELP = "List the base stats of a specific body. " + DUMPSTATS_ARGS,
            DUMPMODS_HELP = "Lists installed mods and mods that are required by everyone." + NO_ARGS,
            EVOLVE_LEMURIAN_HELP = "Triggers evolution for Artifact of Devotion Lemurians." + PLAYER_OR_ALL_OPTIONAL_ARGS,
            FAMILYEVENT_HELP = "Forces a family event to occur during the next stage. " + NO_ARGS,
            FIXEDTIME_HELP = "Sets the run timer to the specified value. " + FIXEDTIME_ARGS,
            FORCEWAVE_HELP = "Set the next wave prefab. Leave empty to see all options. " + FORCEWAVE_ARGS,
            GIVEBUFF_HELP = "Gives the specified buff to a character. A duration of 0 means permanent. " + GIVEBUFF_ARGS,
            GIVEDOT_HELP = "Gives the specified DoT to a character. " + GIVEDOT_ARGS,
            GIVEEQUIP_HELP = "Gives the specified equipment to a target. " + GIVEEQUIP_ARGS,
            RANDOMEQUIP_HELP = "Gives a random equipment to a target. " + RANDOMEQUIP_ARGS,
            GIVEITEM_HELP = "Gives the specified item to a target. " + GIVEITEM_ARGS,
            GIVELUNAR_HELP = "Gives amount of lunar coin to you. " + GIVELUNAR_ARGS,
            GIVEVOID_HELP = "Gives amount of void markers to you. " + GIVELUNAR_ARGS,
            GIVEMONEY_HELP = "Gives the specified amount of money to the specified player. " + GIVEMONEY_ARGS,
            NO_MONEY_HELP = "Sets money to 0 for specified player. " + GIVEMONEY_ARGS,
            ALLMONEY_HELP = "Sets money to 2'000'000'000 for specified player. " + GIVEMONEY_ARGS,
            GOD_HELP = "Become invincible. " + ENABLE_ARGS,
            GODENEMY_HELP = "All monster team members become invincible. " + ENABLE_ARGS,
            SETSTAT_HELP = "Sets the base stat to the specified value, or reset it if no value given. Use respawn to undo all changes on self." + SETSTATS_ARGS,
            GIVEDRONE_HELP = "Summons the specified drone to a target. " + GIVEDRONE_ARGS,
            REMOVEALLDRONES_HELP = "Removes all drones from the target. " + REMOVEALLDRONES_ARGS,
             
            HEAL_HELP = "Heal yourself or another target. " + HEAL_ARGS,
            HURT_HELP = "Deal generic damage to yourself or another target. " + HURT_ARGS,
            KICK_HELP = "Kicks the specified player from the session. " + PLAYER_ARGS,
            KILLALL_HELP = "Kill all entities on the specified team. " + KILLALL_ARGS,
            LISTAI_HELP = "List all Masters and their language invariants. " + LISTQUERY_ARGS,
            LISTARTIFACT_HELP = "List all Artifacts and their language invariants. " + LISTQUERY_ARGS,
            LISTDIFFICULTY_HELP = "List all Difficulties and their language invariants. " + LISTQUERY_ARGS,
            LISTBODY_HELP = "List all Bodies and their language invariants. " + LISTQUERY_ARGS,
            LISTBUFF_HELP = "List all Buffs and whether they stack. " + LISTQUERY_ARGS,
            LISTDIRECTORCARDS_HELP = "List all Director Cards. " + LISTQUERY_ARGS,
            LISTDOT_HELP = "List all DoTs. " + LISTQUERY_ARGS,
            LISTELITE_HELP = "List all Elites and their language invariants. " + LISTQUERY_ARGS,
            LISTEQUIP_HELP = "List all equipment and their availability. " + LISTQUERY_ARGS,
            LISTDRONE_HELP = "List all drones and their availability. " + LISTQUERY_ARGS,
            LISTPICKUP_HELP = "List all pickups and their availability. " + LISTQUERY_ARGS,
            LISTINTERACTABLE_HELP = "Lists all interactables. " + LISTQUERY_ARGS,
            LISTITEMTIER_HELP = "List all item tiers. " + LISTQUERY_ARGS,
            LISTITEM_HELP = "List all items and their availability. " + LISTQUERY_ARGS,
            LISTPLAYER_HELP = "List all players and their ID. " + LISTQUERY_ARGS,
            LISTSCENE_HELP = "List all scenes and their language invariants. " + LISTQUERY_ARGS,
            LISTSKIN_HELP = "List all bodies with skins. " + LISTSKIN_ARGS,
            LISTSURVIVOR_HELP = "List all survivors and their body/ai names. " + LISTQUERY_ARGS,
            LISTTEAM_HELP = "List all Teams and their language invariants. " + LISTQUERY_ARGS,
            LOADOUTSKIN_HELP = "Change your loadout's skin.  " + LOADOUTSKIN_ARGS,
            LOADOUTSKILL2_HELP = "Sets your loadout's skill variant for the given slot.  " + LOADOUTSKILL_ARGS,
            LOCKEXP_HELP = "Prevent Experience gain. " + ENABLE_ARGS,
            NOCOOLDOWN_HELP = "Toggles skill cooldowns of the target. " + PLAYER_OR_PINGED,
            MACRO_DTPEACE_HELP = "Kills all enemies, voids, disables enemies spawning and enables godmode.",
            MACRO_DTZOOM_HELP = "Gives you 20 hooves and 200 feathers for getting around quickly.",
            MACRO_SCANNER_HELP = "Gives you 100 boostEquipmentRecharge and the Radar Scanner equipment to easily search stages.",
            MACRO_DTCLEANSE_HELP = "Removes all your buffs, timed buffs & dots.",

            MACRO_LATEGAME_HELP = "Sets the current run to the 'lategame' as defined by HG. This command is DESTRUCTIVE.",
            MACRO_MIDGAME_HELP = "Sets the current run to the 'midgame' as defined by HG. This command is DESTRUCTIVE.",
            NEXTBOSS_HELP = "Sets the next teleporter/simulacrum boss to the specified boss. " + NEXTBOSS_ARGS,
            NEXTSTAGE_HELP = "Forces a stage change to the specified stage. " + NEXTSTAGE_ARGS,
            NEXTWAVE_HELP = "Advance to the next Simulacrum wave. " + NO_ARGS,
            NOCLIP_HELP = "Allow flying and going through objects. Sprinting will double the speed. " + ENABLE_ARGS,
            NOENEMIES_HELP = "Prevent Monster spawning. " + ENABLE_ARGS,
            NOINTERACTABLES_HELP = "Prevent random Interactables from spawning. " + ENABLE_ARGS,
            PERM_ENABLE_HELP = "Enable or disable the permission system." + ENABLE_ARGS,
            PERM_MOD_HELP = "Change the permission level of the specified playerid/username" + PERM_MOD_ARGS,
            PERM_RELOAD_HELP = "Reload the permission system, updates user and commands permissions.",
            POSTSOUNDEVENT_HELP = "Post a sound event to the AkSoundEngine (WWise) either by its event name or event ID. " + POSTSOUNDEVENT_ARGS,
            PREVENT_PROFILE_WRITING_HELP = "Prevent saving the user profile to avoid bogus data. " + ENABLE_ARGS,
            RANDOMITEM_HELP = "Generate random items from the available item tiers. " + RANDOMITEM_ARGS,
            RELOADCONFIG_HELP = "Reload all default config files from all loaded plugins.",
            REMOVEALLBUFFS_HELP = "Removes all buffs from a character. " + REMOVEALLBUFFS_ARGS,
            REMOVEALLDOTS_HELP = "Removes all DoTs from a character. " + REMOVEALLDOTS_ARGS,
            REMOVEALLITEMS_HELP = "Removes all items from a target. " + REMOVEALLITEMS_ARGS,
            REMOVEBUFF_HELP = "Removes a specified buff from a character. Timed buffs prioritise the longest expiration stack. " + REMOVEBUFF_ARGS,
            REMOVEBUFFSTACKS_HELP = "Removes all stacks of a specified buff from a character. " + REMOVEBUFFSTACKS_ARGS,
            REMOVEDOT_HELP = "Remove a DoT stack with the longest expiration from a character. " + REMOVEDOT_ARGS,
            REMOVEDOTSTACKS_HELP = "Remove all stacks of a specified DoT from a character. " + REMOVEDOTSTACKS_ARGS,
            REMOVEEQUIP_HELP = "Removes the equipment from a target. " + REMOVEEQUIP_ARGS,
            REMOVEITEM_HELP = "Removes the specified quantities of an item from a target. " + GIVEITEM_ARGS,
            REMOVEITEMSTACKS_HELP = "Removes all the stacks of a specified item from a target. " + REMOVEITEMSTACKS_ARGS,
            RESPAWN_HELP = "Respawns the specified player. " + RESPAWN_ARGS,
            RESTOCKEQUIP_HELP = "Restock charges for the current equipment. " + RESTOCKEQUIP_ARGS,
            RUNSETWAVESCLEARED_HELP = "Set the Simulacrum waves cleared. Must be positive. " + RUNSETWAVESCLEARED_ARGS,
            SEED_HELP = "Gets/Sets the game seed until game close. Use 0 to reset to vanilla generation. " + SEED_ARGS,
            SETARTIFACT_HELP = "Enable/disable an Artifact. " + SETARTIFACT_ARGS,
            SETDIFFICULTY_HELP = "Sets the runs selected difficulty. " + SETDIFFICULTY_ARGS,
            SPAWNAS_HELP = "Respawn the specified player using the specified body prefab. " + SPAWNAS_ARGS,
            SPAWNAI_HELP = "Spawns the specified CharacterMaster. " + SPAWNAI_ARGS,
            SPAWNBODY_HELP = "Spawns the specified dummy body. " + SPAWNBODY_ARGS,
            SPAWNINTERACTABLE_HELP = "Spawns the specified interactable. List_Interactable for options. " + SPAWNINTERACTABLE_ARGS,
            SPAWNPORTAL_HELP = "Spawns a portal in front of the player. " + SPAWNPORTAL_ARGS,
            STOPTIMER_HELP = "Pause/unpause the run timer. " + ENABLE_ARGS,
            TIMESCALE_HELP = "Sets the Time Delta. " + TIMESCALE_ARGS,
            TRUEKILL_HELP = "Kill the entity bypassing revives, buddha & godmode. " + PLAYERPINGED_OR_ALL,
            TOGGLETIME_HELP = "Toggles timescale between 0 and normal value. " + NO_ARGS,
            TOGGLEMODE_HELP = "Turn off your model for screenshots" + NO_ARGS,
            TOGGLEHUD_HELP = "Toggle hud_enable. Enable/disable the HUD." + NO_ARGS
            ;

        // Messages
        public const string
            CREATEPICKUP_AMBIGIOUS = "Found multiple results. Please be more precise or specify using 'item', 'equip', 'drone'\n{0}",
            CREATEPICKUP_NOTFOUND = "Could not find any item, equipment or drone with that name or index.",
            CREATEPICKUP_SUCCESS_1 = "Successfully created the pickup {0}.",
            CREATEPICKUP_SUCCESS_2 = "Successfully created a potential with {0} options.",
            GIVELUNAR_2 = "{0} {1} lunar coin(s).",
            GIVEVOIDC_2 = "{0} {1} void marker(s).",
            GIVEOBJECT = "Gave {0} {1} to {2}.",
            GIVEDRONE = "Summoned {0} {1} (Tier {3}) to {2}.",
            REMOVEDRONES = "Removed {0} drones from {1}.",
            REMOVEDEQUIP = "Removed current Equipment from {0}.",
            Kill_MINIONS = "Killed all minions owned by {0}.",
            OBSOLETEWARNING = "This command has become obsolete and will be removed in the next version. ",
            NETWORKING_OTHERPLAYER_4 = "{0}({1}) issued: {2} {3}",
            NOMESSAGE = "Yell at the modmakers if you see this message!",
            PARTIALIMPLEMENTATION_WARNING = "WARNING: PARTIAL IMPLEMENTATION. WIP.",
            PLAYER_DEADRESPAWN = "Player will spawn as the specified body next round. " + USE_RESPAWN,
            PLAYER_SKINCHANGERESPAWN = "Player will spawn with the specified skin next round. " + USE_RESPAWN,
            REMOVEOBJECT = "Removed {0} {1} from {2}.",
            RUNSETSTAGESCLEARED_HELP = "Sets the amount of stages cleared. This does not change the current stage.",
            TEMP = "{0} <color=#53E9FF>temporary</color>",
            SETTING_ENABLED = "{0} <color=green>enabled</color>",
            SETTING_DISABLED = "{0} <color=red>disabled</color>",
            SETTING_ENABLED2 = "<color=red>Enabled</color>",
            SETTING_DISABLED2 = "<color=green>Disabled</color>",
            SPAWN_ATTEMPT_1 = "Attempting to spawn: {0}",
            SPAWN_ATTEMPT_2 = "Attempting to spawn {0}: {1}",
            USE_RESPAWN = "Use 'respawn' to skip the wait."
            ;

        // Errors
        public const string
            BODY_NOTFOUND = "Specified body not found. Please use list_body for options.",
            DOTCONTROLLER_NOTFOUND = "The selected target has no DoTs.",
            ELITE_NOTFOUND = "Elite type not recognized. Please use list_elite for options.",
            EXPANSION_LOCKED = "An expansion is required for this {0}: {1}",
            INSUFFICIENT_ARGS = "Insufficient number of arguments. ",
            INTERACTABLE_NOTFOUND = "Interactable not found. Please use list_interactables for options.",
            INVALID_ARG_VALUE = "Invalid value for {0}.",
            INVENTORY_ERROR = "The selected target has no inventory.",
            NEGATIVE_ARG = "Negative value for {0} encountered. It needs to be zero or higher.",
            NOCONNECTION_ERROR = "Not connected to a server.",
            NOMATCH_ERROR = "No {0} found that match \"{1}\".",
            NOTINARUN_ERROR = "This command only works when in a Run!",
            NOTINASIMULACRUMRUN_ERROR = "Must be in a Simulacrum Run!",
            NOTINVOIDFIELDS_ERROR = "Must be on Void Fields!",
            OBJECT_NOTFOUND = "No {0} with the name or index \"{1}\" could be found.",
            PARSE_ERROR = "Unable to parse {0} to {1}.",
            PINGEDBODY_NOTFOUND = "Pinged target not found. Either the last ping was not a character, or it has been destroyed since.",
            PLAYER_NOTFOUND = "Specified player not found or isn't alive. Please use list_player for options.",
            SPAWN_ERROR = "Could not spawn: ",
            STAGE_NOTFOUND = "Stage not found. Please use list_scene for options.",
            TEAM_NOTFOUND = "Team type not found. Please use list_team for options."
            ;

        // Keywords
        public const string
            ALL = "ALL",
            ALLY = "ALLY",
            BOTH = "BOTH",
            COIN_LUNAR = "LUNARCOIN",
            COIN_VOID = "VOIDCOIN",
            DEFAULT_VALUE = "",
            DEVOTION = "DEVOTION",
            EQUIP = "EQUIP",
            DRONE = "DRONE",
            PICKUP = "PICKUP",
            EVOLUTION = "EVOLUTION",
            ITEM = "ITEM",
            PINGED = "PINGED",
            RANDOM = "RANDOM",
            NONE = "NONE",
            SIMULACRUM = "SIMULACRUM",
            VOIDFIELDS = "VOIDFIELDS"
            ;

        // Permissions
        public const string
            PS_ARGUSER_HAS_MORE_PERM = "Specified user {0} has a greater permission level than you.",
            PS_ARGUSER_HAS_SAME_PERM = "Specified user {0} has the same permission level as you.",
            PS_NO_REQUIRED_LEVEL = "You don't have the required permission {0} to use this command."
            ;

        // Dedicated server
        public const string
            DS_INVALIDARG = "This command doesn't support the '{0}' argument from a dedicated server.",
            DS_NOTAVAILABLE = "This command doesn't make sense to run from a dedicated server.",
            DS_NOTYETIMPLEMENTED = "This command has not yet been implemented to be run from a dedicated server,"
            ;

    }
}
